# Generated by Django 4.2.8 on 2024-05-23 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_mozip_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mozip',
            name='applicant',
        ),
        migrations.AddField(
            model_name='mozip',
            name='applicant',
            field=models.ManyToManyField(blank=True, related_name='applicated', to=settings.AUTH_USER_MODEL),
        ),
    ]
