# Generated by Django 4.2.8 on 2024-05-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_cinema_alter_article_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='article',
            name='movie',
        ),
    ]
