# Generated by Django 4.2.8 on 2024-05-21 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('articles', '0002_alter_comment_article_alter_comment_cinema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
