# Generated by Django 4.2.8 on 2024-05-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_cinema_remove_article_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
    ]
