# Generated by Django 4.2.8 on 2024-05-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='job',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
