
# Generated by Django 4.2.8 on 2024-05-16 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('img_src', models.CharField(max_length=100)),
                ('age', models.TextField()),
                ('director', models.TextField()),
                ('keywords', models.TextField()),
                ('length', models.CharField(max_length=20)),
                ('genre', models.TextField()),
                ('making_year', models.CharField(max_length=10)),
                ('detail', models.TextField()),
                ('cinemas', models.TextField()),
                ('like_users', models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('recent_movies', models.ManyToManyField(related_name='recent_cinemas', to='movies.movie')),
            ],
        ),
    ]
